var date = new Date();
var day = new Date().getDay();
var days = [
  "SUN",
  "MON",
  "TUE",
  "WED",
  "THU",
  "FRI",
  "SAT",
  "SUN",
  "MON",
  "TUE",
  "WED",
  "THU",
  "FRI",
  "SAT",
];
var months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Sep",
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];
const ChooseTimeData = [
  {
    id: "1",
    setDate: date.setDate(date.getDate()),
    date: date.getDate(),
    day: days[day],
    // month: date.getMonth(),
    months: months[date.getMonth()],
    year: date.getFullYear(),
  },
  {
    id: "2",
    setDate: date.setDate(date.getDate() + 1),
    date: date.getDate(),
    day: days[day + 1],
    // month: date.getMonth(),
    months: months[date.getMonth()],
    year: date.getFullYear(),
  },
  {
    id: "3",
    setDate: date.setDate(date.getDate() + 1),
    date: date.getDate(),
    day: days[day + 2],
    // month: date.getMonth(),
    months: months[date.getMonth()],
    year: date.getFullYear(),
  },
  {
    id: "4",
    setDate: date.setDate(date.getDate() + 1),
    date: date.getDate(),
    day: days[day + 3],
    // month: date.getMonth(),
    months: months[date.getMonth()],
    year: date.getFullYear(),
  },
  {
    id: "5",
    setDate: date.setDate(date.getDate() + 1),
    date: date.getDate(),
    day: days[day + 4],
    // month: date.getMonth(),
    months: months[date.getMonth()],
    year: date.getFullYear(),
  },
  {
    id: "6",
    setDate: date.setDate(date.getDate() + 1),
    date: date.getDate(),
    day: days[day + 5],
    // month: date.getMonth(),
    months: months[date.getMonth()],
    year: date.getFullYear(),
  },
  {
    id: "7",
    setDate: date.setDate(date.getDate() + 1),
    date: date.getDate(),
    day: days[day + 6],
    // month: date.getMonth(),
    months: months[date.getMonth()],
    year: date.getFullYear(),
  },
];
export default ChooseTimeData;
